# fly.toml app configuration file for QSOWhat
# Configured for 2 VMs under Fly.io free tier
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'qsowhat'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  # Note: Set SESSION_SECRET using: fly secrets set SESSION_SECRET="$(openssl rand -hex 32)"

[deploy]
  release_command = "python -c 'print(\"QSOWhat deployment starting...\")'"

[processes]
  app = "gunicorn --bind 0.0.0.0:5000 --workers 1 --timeout 60 --preload main:app"