# fly.toml app configuration file generated for qsowhat on 2025-07-24T18:27:43-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'qsowhat'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 2
  processes = ['app']

[[vm]]
  cpu_kind = "shared" # Use shared CPU, which is part of the free tier
  cpus = 1            # 1 CPU core
  memory = "256mb"    # 256 MB of RAM (common free tier limit per VM)
  size = "shared-cpu-1x" # The specific size that aligns with the free tier

[[vm]]
  cpu_kind = "shared" # Use shared CPU, which is part of the free tier
  cpus = 1            # 1 CPU core
  memory = "256mb"    # 256 MB of RAM (common free tier limit per VM)
  size = "shared-cpu-1x" # The specific size that aligns with the free tier
